import "./globals.css";
import type { Metadata } from "next";

import localFont from "next/font/local";
const Gilroy = localFont({ src: "../public/fonts/Gilroy-Light.otf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Gilroy.className}>{children}</body>
    </html>
  );
}
